# -*- coding: utf-8 -*-
# 133 míst měření rychlosti MP Praha (č.j. KRPA-203411-1/ČJ-2026-0000DŽ, účinnost 1. 9. 2026)
# cat: A=hlídkové měření (Bezpečná místa), B=úsekové měřiče, C=úsekové i stacionární, D=stacionární
# q = seznam dotazů pro Nominatim (průměr nalezených bodů), fix = pevné souřadnice

ITEMS = [
 dict(n=1, cat="A", mc="Praha 1", t="Dvořákovo nábřeží", d="od křiž. s ul. Nové Mlýny po vjezd na nám. Curieových", q=["Nové Mlýny", "náměstí Curieových"]),
 dict(n=2, cat="A", mc="Praha 1", t="Jelení, Mariánské hradby", d="mezi křiž. s ul. U Brusnice a křiž. s ul. Badeniho, Chotkova", q=["Mariánské hradby", "U Brusnice", "Badeniho"]),
 dict(n=3, cat="A", mc="Praha 2", t="Italská", d="mezi křiž. s ul. Na Smetance a křiž. s ul. Lichnická", q=["Na Smetance", "Lichnická"]),
 dict(n=4, cat="A", mc="Praha 2", t="Sekaninova", d="mezi křiž. s ul. Svatoplukova a vjezdem na Ostrčilovo nám.", q=["Sekaninova"]),
 dict(n=5, cat="A", mc="Praha 2", t="V Pevnosti", d="mezi Táborskou a Leopoldovou bránou", q=["V Pevnosti"]),
 dict(n=6, cat="A", mc="Praha 2", t="K Rotundě", d="mezi křiž. s ul. V Pevnosti a křiž. s ul. Štulcova, Soběslavova", q=["K Rotundě"]),
 dict(n=7, cat="A", mc="Praha 3", t="Hartigova", d="mezi domem č. 211 a křiž. s ul. Na vrcholu", q=["Hartigova 211", "Na vrcholu"]),
 dict(n=8, cat="A", mc="Praha 3", t="Hartigova", d="mezi domem č. 198 a křiž. s ul. Na Chmelnici", q=["Hartigova 198", "Na Chmelnici"]),
 dict(n=9, cat="A", mc="Praha 3", t="Hartigova", d="mezi domem č. 238 a křiž. s ul. Spojovací", q=["Hartigova 238"]),
 dict(n=10, cat="A", mc="Praha 4", t="Vídeňská", d="v celé své délce", q=["Vídeňská"]),
 dict(n=11, cat="A", mc="Praha 4", t="Vrbova", d="v celé své délce", q=["Vrbova"]),
 dict(n=12, cat="A", mc="Praha 4", t="Na Chodovci", d="v celé své délce", q=["Na Chodovci"]),
 dict(n=13, cat="A", mc="Praha 4", t="Jeremenkova", d="v celé své délce", q=["Jeremenkova"]),
 dict(n=14, cat="A", mc="Praha 4", t="Zálesí", d="v celé své délce", q=["Zálesí, Praha 4"]),
 dict(n=15, cat="A", mc="Praha 4", t="Čiklova", d="mezi SVO č. 409730 a SVO č. 410347", q=["Čiklova"]),
 dict(n=16, cat="A", mc="Praha 4", t="Petra Rezka", d="v celé své délce", q=["Petra Rezka"]),
 dict(n=17, cat="A", mc="Praha 5", t="Plzeňská", d="mezi SVO č. 501 509 a křiž. s ul. U Kavalírky", q=["U Kavalírky"]),
 dict(n=18, cat="A", mc="Praha 5", t="Podbělohorská", d="mezi domem č. 22 a domem č. 26", q=["Podbělohorská 22", "Podbělohorská"]),
 dict(n=19, cat="A", mc="Praha 5", t="Radlická", d="mezi křiž. s ul. Stará Stodůlecká a křiž. s ul. V Zářezu", q=["Stará Stodůlecká", "V Zářezu"]),
 dict(n=20, cat="A", mc="Praha 16", t="K Cementárně (Pod Klapicí)", d="mezi křiž. s ul. Pod Velkým hájem a křiž. s ul. Prvomájová", q=["Pod Velkým hájem", "Prvomájová"]),
 dict(n=21, cat="A", mc="Praha 16", t="Elišky Přemyslovny (Na Baních)", d="mezi křiž. s ul. Zvonařská a křiž. s ul. Faltysova", q=["Zvonařská", "Faltysova"]),
 dict(n=22, cat="A", mc="Praha 16", t="Radotínská", d="mezi domem č. 18 a domem č. 69", q=["Radotínská"]),
 dict(n=23, cat="A", mc="Praha 16", t="Karlická", d="v celé své délce", q=["Karlická"]),
 dict(n=24, cat="A", mc="Praha 16", t="Zderazská", d="mezi křiž. s ul. Otínská a křiž. s ul. Karlická", q=["Otínská"]),
 dict(n=25, cat="A", mc="Praha 16", t="Výpadová", d="mezi křiž. s ul. Přeštínská a křiž. s ul. Matějovského", q=["Přeštínská", "Matějovského"]),
 dict(n=26, cat="A", mc="Praha 6", t="Na Vypichu", d="v celé své délce", q=["Na Vypichu"]),
 dict(n=27, cat="A", mc="Praha 6", t="Ruzyňská", d="v celé své délce", q=["Ruzyňská"]),
 dict(n=28, cat="A", mc="Praha 6", t="Kladenská", d="v celé své délce", q=["Kladenská"]),
 dict(n=29, cat="A", mc="Praha 6", t="Kamýcká", d="v celé své délce", q=["Kamýcká"]),
 dict(n=30, cat="A", mc="Praha 6", t="Nebušická", d="mezi křiž. s ul. Na Malé Šárce a nám. Padlých", q=["Na Malé Šárce", "náměstí Padlých"]),
 dict(n=31, cat="A", mc="Praha 6", t="Sibeliova", d="v celé své délce", q=["Sibeliova"]),
 dict(n=32, cat="A", mc="Praha 6", t="Suchdolská", d="v celé své délce", q=["Suchdolská, Suchdol"]),
 dict(n=33, cat="A", mc="Praha 6", t="Vlastina", d="v celé své délce", q=["Vlastina"]),
 dict(n=34, cat="A", mc="Praha 6", t="Pod Marjánkou", d="v celé své délce", q=["Pod Marjánkou"]),
 dict(n=35, cat="A", mc="Praha 6", t="Pod Novým lesem", d="v celé své délce", q=["Pod Novým lesem"]),
 dict(n=36, cat="A", mc="Praha 6", t="Sestupná", d="v celé své délce", q=["Sestupná"]),
 dict(n=37, cat="A", mc="Praha 6", t="Radimova", d="mezi křiž. s ul. Na Zástřelu a křiž. s ul. Kusá", q=["Radimova"]),
 dict(n=38, cat="A", mc="Praha 7", t="Trojská", d="mezi křiž. s ul. Pod Lisem a křiž. U Trojského zámku", q=["Pod Lisem", "U Trojského zámku"]),
 dict(n=39, cat="A", mc="Praha 7", t="Bubenské nábřeží", d="v celé své délce", q=["Bubenské nábřeží"]),
 dict(n=40, cat="A", mc="Praha 7", t="Ortenovo nám.", d="mezi křiž. s ul. Přívozní a křiž. Ortenovo nám. × Vrbenského", q=["Ortenovo náměstí"]),
 dict(n=41, cat="A", mc="Praha 7", t="nábřeží Kpt. Jaroše", d="v celé své délce", q=["nábřeží Kapitána Jaroše"]),
 dict(n=42, cat="A", mc="Praha 7", t="Veletržní", d="mezi Letenským náměstím a křiž. s ul. Dukelských hrdinů", q=["Letenské náměstí", "Veletržní"]),
 dict(n=43, cat="A", mc="Praha 8", t="Žernosecká", d="mezi křiž. s ul. Burešova a křiž. s ul. Famfulíkova", q=["Žernosecká"]),
 dict(n=44, cat="A", mc="Praha 8", t="Horňátecká", d="mezi křiž. s ul. Přemyšlenská a křiž. s ul. Klapkova", q=["Horňátecká"]),
 dict(n=45, cat="A", mc="Praha 8", t="Čimická", d="mezi křiž. s ul. Tišická a křiž. s ul. Mlazická", q=["Tišická", "Mlazická"]),
 dict(n=46, cat="A", mc="Praha 8", t="Lodžská", d="v celé své délce", q=["Lodžská"]),
 dict(n=47, cat="A", mc="Praha 9", t="Lovosická", d="mezi domem č. 711/30 a křiž. s ul. Zásadská", q=["Lovosická", "Zásadská"]),
 dict(n=48, cat="A", mc="Praha 9", t="Českobrodská", d="mezi křiž. s ul. Pod Táborem a domem č. 34/7", q=["Pod Táborem"]),
 dict(n=49, cat="A", mc="Praha 9", t="Poděbradská", d="mezi SVO č. 900 288 a domem č. 531/50", q=["Poděbradská 531"]),
 dict(n=50, cat="A", mc="Praha 9", t="Mladoboleslavská", d="mezi křiž. s ul. Semčická a křiž. s ul. Nymburská", q=["Semčická", "Nymburská"]),
 dict(n=51, cat="A", mc="Praha 9", t="Mladoboleslavská", d="mezi křiž. s ul. Lohenická a křiž. s ul. Ronovská", q=["Lohenická", "Ronovská"]),
 dict(n=52, cat="A", mc="Praha 9", t="Nad Krocínkou", d="v celé své délce", q=["Nad Krocínkou"]),
 dict(n=53, cat="A", mc="Praha 18", t="Schoellerova", d="mezi domem č. 876/14 a domem č. 954/55", q=["Schoellerova 876", "Schoellerova"]),
 dict(n=54, cat="A", mc="Praha 19", t="K Cihelně", d="mezi domem č. 59/2 a křiž. s ul. Pod garážemi", q=["K Cihelně", "Pod garážemi"]),
 dict(n=55, cat="A", mc="Praha 19", t="Polabská", d="mezi křiž. s ul. Za Můstkem a křiž. s ul. Na Kačence", q=["Polabská", "Na Kačence"]),
 dict(n=56, cat="A", mc="Praha 10", t="Práčská", d="mezi SVO č. 002 853 a SVO č. 002 843", q=["Práčská"]),
 dict(n=57, cat="A", mc="Praha 10", t="Práčská", d="mezi křiž. s ul. Aubrechtové a SVO č. 002 856", q=["Aubrechtové"]),
 dict(n=58, cat="A", mc="Praha 10", t="Švehlova", d="mezi SVO č. 007 532 a domem č. 15", q=["Švehlova 15", "Švehlova"]),
 dict(n=59, cat="A", mc="Praha 10", t="Průběžná", d="mezi domem č. 56 a domem č. 74", q=["Průběžná 56", "Průběžná"]),
 dict(n=60, cat="A", mc="Praha 10", t="Vršovická", d="mezi křiž. s ul. U Vršovického nádraží a křiž. s ul. Perucká", q=["U Vršovického nádraží", "Perucká"]),
 dict(n=61, cat="A", mc="Praha 11", t="Výstavní", d="mezi SVO č. 422 207 a SVO č. 422 230", q=["Výstavní"]),
 dict(n=62, cat="A", mc="Praha 11", t="U Kunratického lesa", d="mezi SVO č. 426 435 a SVO č. 426 443", q=["U Kunratického lesa"]),
 dict(n=63, cat="A", mc="Praha 11", t="Květnového vítězství", d="mezi domem č. 57 a domem č. 53", q=["Květnového vítězství 57", "Květnového vítězství"]),
 dict(n=64, cat="A", mc="Praha 11", t="Ke Kateřinkám", d="mezi domem č. 1412 a domem č. 1403", q=["Ke Kateřinkám"]),
 dict(n=65, cat="A", mc="Praha 12", t="Generála Šišky", d="mezi křiž. s ul. Dolnocholupická a křiž. s ul. Novodvorská", q=["Generála Šišky"]),
 dict(n=66, cat="A", mc="Praha 12", t="Durychova", d="mezi křiž. s ul. Novodvorská a křiž. s ul. U Kamýku", q=["Durychova", "U Kamýku"]),
 dict(n=67, cat="A", mc="Praha 12", t="Novodvorská", d="mezi křiž. s ul. Freiwaldova a křiž. s ul. Písnická", q=["Freiwaldova"]),
 dict(n=68, cat="A", mc="Praha 12", t="Československého exilu", d="mezi křiž. s ul. Pavelkova a křiž. s ul. Platónova", q=["Československého exilu"]),
 dict(n=69, cat="A", mc="Praha 13", t="Plzeňská", d="mezi křiž. s ul. Jeremiášova, Slánská a křiž. s ul. Ke Koh-i-nooru", q=["Ke Koh-i-nooru"]),
 dict(n=70, cat="A", mc="Praha 13", t="Hrozenkovská", d="mezi křiž. s ul. Na Radosti a křiž. s ul. Věstonická", q=["Hrozenkovská", "Věstonická"]),
 dict(n=71, cat="A", mc="Praha 14", t="Broumarská", d="mezi křiž. s ul. Vajgarská a křiž. s ul. Stupská", q=["Broumarská"]),
 dict(n=72, cat="A", mc="Praha 14", t="Cíglerova", d="mezi křiž. s ul. Bratří Venclíků a křiž. s ul. Pospíchalova", q=["Cíglerova"]),
 dict(n=73, cat="A", mc="Praha 14", t="Ocelkova", d="mezi křiž. s ul. Dobrovolného, Generála Janouška a bližší křiž. s ul. Bryksova", q=["Ocelkova"]),
 dict(n=74, cat="A", mc="Praha 21", t="Slavětínská", d="v celé své délce", q=["Slavětínská"]),
 dict(n=75, cat="A", mc="Praha 21", t="Staroklánovická", d="v celé své délce", q=["Staroklánovická"]),
 dict(n=76, cat="A", mc="Praha 21", t="Rohožnická", d="mezi křiž. s ul. Miletická a křiž. s ul. Novosibřinská", q=["Rohožnická"]),
 dict(n=77, cat="A", mc="Praha 21", t="Zaříčanská", d="mezi křiž. s ul. Chyjická a křiž. s ul. Novosibřinská", q=["Zaříčanská"]),
 dict(n=78, cat="A", mc="Praha 21", t="Podzámecká", d="mezi křiž. s ul. Kounovská a křiž. s ul. V Lipách", q=["Podzámecká, Koloděje"]),
 dict(n=79, cat="A", mc="Praha 15", t="Hornoměcholupská", d="mezi křiž. s ul. Kunická a křiž. s ul. K Lesoparku", q=["Kunická"]),
 dict(n=80, cat="A", mc="Praha 15", t="Starodubečská", d="mezi křiž. s ul. U Hodin a křiž. s ul. Za Pavilonem", q=["Starodubečská"]),
 dict(n=81, cat="A", mc="Praha 15", t="Euklidova", d="mezi sloupy VO č. 011663 a 011660", q=["Euklidova"]),
 dict(n=82, cat="A", mc="Praha 22", t="Mírová", d="mezi křiž. s ul. Do Hlinek a křiž. s ul. V Milíři", q=["Do Hlinek", "V Milíři"]),
 dict(n=83, cat="A", mc="Praha 22", t="Květnového povstání", d="mezi hotelem Park Holliday a křiž. s ul. K Pitkovicům", q=["K Pitkovicům"]),

 dict(n=84, cat="B", mc="Praha 5, 6", t="Strahovský tunel", d="směr tunel Mrázovka, mezi 1150,3 m a 406,8 m", q=["Strahovský tunel"], off=(-40, 0)),
 dict(n=85, cat="B", mc="Praha 5, 6", t="Strahovský tunel", d="směr ul. Patočkova, mezi 392,9 m a 1160 m", q=["Strahovský tunel"], off=(40, 0)),
 dict(n=86, cat="B", mc="Praha 5, 6", t="Tunel Mrázovka", d="směr ul. Dobříšská, mezi 5055,3 m a 4591,3 m", q=["tunel Mrázovka"], off=(-40, 0)),
 dict(n=87, cat="B", mc="Praha 5, 6", t="Tunel Mrázovka", d="směr Strahovský tunel, mezi 4555,2 m a 5139,6 m", q=["tunel Mrázovka"], off=(40, 0)),
 dict(n=88, cat="B", mc="Praha 5", t="Dobříšská", d="směr Zlíchovský tunel, mezi 3465 m a 2944 m", q=["Dobříšská"], off=(-40, 0)),
 dict(n=89, cat="B", mc="Praha 5", t="Dobříšská", d="směr tunel Mrázovka, mezi 2935 m a 3459 m", q=["Dobříšská"], off=(40, 0)),
 dict(n=90, cat="B", mc="Praha 8", t="Ústecká", d="směr z centra, mezi SVO č. 807347 a č. 807359", q=["Ústecká"]),
 dict(n=91, cat="B", mc="Praha 6", t="Bělohorská", d="směr z centra, mezi SVO č. 601596 a č. 601618", q=["Bělohorská"]),
 dict(n=92, cat="B", mc="Praha 6", t="Evropská – Alžírská", d="směr do centra, mezi SVO č. 619837 a č. 619472", q=["Alžírská"], off=(-40, 0)),
 dict(n=93, cat="B", mc="Praha 4", t="Podolské nábřeží", d="směr do centra, mezi SVO č. 401507 a č. 400039", q=["Podolské nábřeží"]),
 dict(n=94, cat="B", mc="Praha 10", t="Jižní spojka – Průmyslová", d="směr Barrandovský most, mezi SVO č. 006343 a č. 006304", fix=(50.0605, 14.5245)),
 dict(n=95, cat="B", mc="Praha 4", t="Jižní spojka – Barrandovský most", d="směr Krč, mezi SVO č. 402879 a č. 402889", fix=(50.0340, 14.4160)),
 dict(n=96, cat="B", mc="Praha 4", t="Jižní spojka – Krč – Chodovská", d="směr Teplice, mezi SVO č. 402887 a č. 403012", fix=(50.0450, 14.4680)),
 dict(n=97, cat="B", mc="Praha 4", t="Jižní spojka – Chodovská", d="směr Teplice, mezi SVO č. 403010 a č. 403045", fix=(50.0520, 14.4950)),
 dict(n=98, cat="B", mc="Praha 9", t="Poděbradská", d="směr do centra, mezi SVO č. 900446 a č. 900425", q=["Poděbradská 580"], off=(-40, 0)),
 dict(n=99, cat="B", mc="Praha 9", t="Poděbradská", d="směr z centra, mezi SVO č. 919696 a č. 900457", q=["Poděbradská 580"], off=(40, 0)),
 dict(n=100, cat="B", mc="Praha 4", t="5. května", d="směr do centra, mezi SVO č. 409912 a č. 409893", q=["5. května, Praha 4"]),
 dict(n=101, cat="B", mc="Praha 5", t="Strakonická", d="směr do centra, mezi SVO č. 521966 a č. 515573", fix=(50.0455, 14.4085)),
 dict(n=102, cat="B", mc="Praha 6", t="Patočkova", d="směr do centra, mezi SVO č. 600761 a č. 600737", q=["Patočkova"]),
 dict(n=103, cat="B", mc="Praha 5", t="Dobříšská – tunel Mrázovka", d="směr Strahovský tunel, mezi 3459 m a 4555,2 m", q=["Dobříšská"], off=(100, 60)),
 dict(n=104, cat="B", mc="Praha 4", t="Jižní spojka – Spořilovská", d="směr 5. května, mezi SVO č. 403037 a č. 403019", fix=(50.0480, 14.4800)),
 dict(n=105, cat="B", mc="Praha 8", t="Argentinská → V Holešovičkách", d="směr z centra, mezi SVO č. 701425 a č. 802597, vč. nájezdu z ul. Povltavská", fix=(50.1095, 14.4430)),
 dict(n=106, cat="B", mc="Praha 8", t="Liberecká → V Holešovičkách", d="směr do centra, od SVO č. 802181 ke SVO č. 802561", q=["Liberecká"]),
 dict(n=107, cat="B", mc="Praha 9", t="Cínovecká", d="směr do centra k ul. Liberecká, mezi SVO č. 806617 a č. 802248", q=["Cínovecká"]),
 dict(n=108, cat="B", mc="Praha 4", t="Spořilovská – Hlavní", d="směr do centra, mezi SVO č. 426831 a č. 415030", q=["Spořilovská"]),
 dict(n=109, cat="B", mc="Praha 6", t="Brusnický tunel", d="směr Troja (– Dejvický tunel), mezi 16,942 km a 17,748 km", q=["Brusnický tunel"], off=(40, 0)),
 dict(n=110, cat="B", mc="Praha 6", t="Dejvický tunel", d="směr Troja (– Bubenečský tunel), mezi 18,12 km a 18,772 km", q=["Dejvický tunel"], off=(40, 0)),
 dict(n=111, cat="B", mc="Praha 6, 7", t="Bubenečský tunel", d="směr Troja, mezi 19,393 km a 21,701 km", q=["Bubenečský tunel"], off=(40, 0)),
 dict(n=112, cat="B", mc="Praha 7, 6", t="Bubenečský tunel", d="směr Strahov (– Dejvický tunel), mezi 21,694 km a 19,418 km", q=["Bubenečský tunel"], off=(-40, 0)),
 dict(n=113, cat="B", mc="Praha 6", t="Dejvický a Brusnický tunel", d="směr Strahov, mezi 18,824 km a 18,178 km", q=["Dejvický tunel"], off=(-40, 0)),
 dict(n=114, cat="B", mc="Praha 6", t="Brusnický tunel", d="směr Strahov, mezi 17,779 km a 16,967 km", q=["Brusnický tunel"], off=(-40, 0)),
 dict(n=115, cat="B", mc="Praha 6", t="Lysolajské údolí", d="mezi SVO č. 610739 a č. 610695", q=["Lysolajské údolí"]),

 dict(n=116, cat="C", mc="Praha 6", t="Horoměřická – V Šáreckém údolí", d="mezi SVO č. 608354 a č. 608364", q=["Horoměřická", "V Šáreckém údolí"]),
 dict(n=117, cat="C", mc="Praha 10", t="U Vršovického hřbitova – Bohdalecká", d="směr do centra, mezi SVO č. 002033 a č. 002018", q=["U Vršovického hřbitova"]),
 dict(n=118, cat="C", mc="Praha 6", t="Libocká", d="mezi SVO č. 611752 a č. 611743", q=["Libocká"]),
 dict(n=119, cat="C", mc="Praha 9", t="Průmyslová – V Chaloupkách", d="mezi SVO č. 908012 a č. 908050", q=["V Chaloupkách"]),
 dict(n=120, cat="C", mc="Praha 5", t="K Barrandovu", d="směr z centra, mezi SVO č. 512155 a č. 512164", q=["K Barrandovu"], off=(40, 0)),
 dict(n=121, cat="C", mc="Praha 5", t="K Barrandovu", d="směr do centra, mezi SVO č. 523579 a č. 512178", q=["K Barrandovu"], off=(-40, 0)),
 dict(n=122, cat="C", mc="Praha 6", t="Evropská – Alžírská", d="směr z centra, mezi SVO č. 617622 a 617632", q=["Alžírská"], off=(40, 0)),

 dict(n=123, cat="D", mc="Praha 6", t="Střešovická", d="směr do centra, mezi SVO č. 600309 a č. 600307", q=["Střešovická"]),
 dict(n=124, cat="D", mc="Praha 5", t="K Barrandovu (× Lamačova, Slavínského)", d="směr do centra, mezi SVO č. 512199 a č. 523581", q=["Lamačova"]),
 dict(n=125, cat="D", mc="Praha 2", t="Legerova (× Rumunská)", d="směr do centra, v místě přechodu pro chodce", q=["Rumunská"]),
 dict(n=126, cat="D", mc="Praha 2", t="Sokolská (× Ječná)", d="směr z centra, v místě přechodu pro chodce", q=["Ječná"]),
 dict(n=127, cat="D", mc="Praha 6", t="Na Okraji", d="směr z centra, před přechodem mezi SVO č. 603618 a č. 603619", q=["Na Okraji"]),
 dict(n=128, cat="D", mc="Praha 6", t="Šantrochova", d="směr do centra, před přechodem u SVO č. 603496", q=["Šantrochova"]),
 dict(n=129, cat="D", mc="Praha 6", t="Na Dlouhém lánu", d="směr z centra, před přechodem u SVO č. 609250", q=["Na Dlouhém lánu"]),
 dict(n=130, cat="D", mc="Praha 4", t="Zálesí", d="směr ul. Novodvorská, před přechodem u SVO č. 412479", q=["Zálesí, Praha 4"], off=(0, -60)),
 dict(n=131, cat="D", mc="Praha 4", t="Zálesí", d="směr Jižní spojka, mezi SVO č. 412482 a č. 412478", q=["Zálesí, Praha 4"], off=(0, 60)),
 dict(n=132, cat="D", mc="Praha 4", t="Modřanská", d="směr do centra, mezi SVO č. 401743 a č. 401741 (zastávka MHD)", q=["Modřanská"], off=(-40, 0)),
 dict(n=133, cat="D", mc="Praha 4", t="Modřanská", d="směr z centra, u SVO č. 401732", q=["Modřanská"], off=(40, 0)),
]
